#!/bin/bash

main_address=~/amid_projects/video-sub-manager/videoSubManager.py
T="$2"

if [ "$1" == "-t" ]; then
	if [ "$3" == "-n" ]; then
		N="$4"
		E="$6"
    fi
fi

if [ "$1" == "-t" ]; then
    if [ "$3" == "-e" ]; then
		N="$6"
		E="$4"
    fi
fi


python3 $main_address -t "$T" -n "$N" -e "$E"
